### PR TITLE
Add Winget, Chocolatey, Scoop, and Homebrew installation instructions

### PR DESCRIPTION
**Pull request by sitiom**
**Which bug report or feature request do these changes address?**
Add Winget, Chocolatey, Scoop, and Homebrew installation instructions for notion-repackaged.

**What does your code do and why?**
Add a reference to it in the installation section.

### CODE REVIEW

**Comment by sitiom** [comment]
PR on Winget: https://github.com/microsoft/winget-pkgs/pull/62256

**Comment by dragonwocky** [comment]
Not merging because we didn't set these packages up, we can't verify them as being up to date or accurate builds of the notion-enhancer so we won't be promoting them as recommended installation methods. If you would like another distribution method to be supported by the notion-enhancer, open an issue/PR over at notion-repackaged to add it to our build/release cycle.

I'm sure they're all probably perfectly fine, but still - I'd rather we were the ones distributing the notion-enhancer rather than relying on externally-maintained packages. That way we're aware of what's released where and we can coordinate updates etc. I'm sure you can understand.

**Comment by sitiom** [comment]
@dragonwocky See https://github.com/notion-enhancer/notion-repackaged/pull/104

**Comment by dragonwocky** [comment]
@sitiom thanks, I'll take care of setting that up when it's time for the next release. Updating the installation instructions can wait until then - there are enough distribution methods available already to support every platform the notion-enhancer runs on, any more are just matters of personal preference.

**Pull request closed without merging**
